(dp1
S'output'
p2
S"<type 'exceptions.NameError'> global name 'shipment' is not defined"
p3
sS'layer'
p4
S'/home/www-data/web2py/applications/reliefList/controllers/default.py'
p5
sS'code'
p6
S'<code object <module> at 0x7f77ce077330, file "/home/www-data/web2py/applications/reliefList/controllers/default.py", line 2>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/www-data/web2py/gluon/restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "/home/www-data/web2py/applications/reliefList/controllers/default.py", line 232, in <module>\n  File "/home/www-data/web2py/gluon/globals.py", line 414, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/www-data/web2py/applications/reliefList/controllers/default.py", line 181, in deliveryChoice\n    session.productIdStripe_data = dict(id=prodId,sI=shipment.rates)\nNameError: global name \'shipment\' is not defined\n'
p11
s.